// ==========================================================================
// BASE DE DATOS DEL JUEGO (CATÁLOGOS Y TEXTOS)
// ==========================================================================

/**
 * storeItems: Objeto masivo (Diccionario) que almacena la información de todos 
 * los productos de las tiendas.
 * Atributos principales:
 * - hunger / happiness: Puntos de estadística que recuperan.
 * - msgLike: Array de frases que dice el profesor si el dado (70%) cae a favor.
 * - msgDislike: Array de quejas que dice si el objeto no le gusta (30%).
 */
const storeItems = {
    pizza: { id: 'pizza', type: 'food', name: 'Pizza', image: 'assets/images/pizza.png', price: 40, hunger: 40, happiness: 15, msgLike: ['¡Me encanta la pizza! 🍕', '¡Mamma mia, qué delicia!', '¡La pizza siempre es buena idea!', '¡Con extra de queso, increíble!', 'La mejor porción de mi vida.', '¡Viernes de pizza adelantado!', '¡Qué maravilla italiana!', '¡Los bordes están súper crujientes!', '¡Me comería tres familiares yo solo!', '¡Un manjar de dioses!', 'Sabe a gloria bendita.'], msgDislike: ['Uf, demasiada grasa para hoy...', 'No me apetece pizza ahora.', 'La masa está un poco dura.', 'Prefería una ensalada.', 'Me va a dar acidez.', 'Le falta piña... es broma.', 'Está fría como el hielo.', 'Demasiada harina para mi estómago.', 'Hoy estoy a dieta, lo siento.'] },
    agua: { id: 'agua', type: 'food', name: 'Agua', image: 'assets/images/agua.png', price: 5, hunger: 5, happiness: 5, msgLike: ['¡Qué refrescante! 💧', 'Justo lo que necesitaba.', '¡Glup, glup! El agua es vida.', 'Súper fresquita.', '¡Mi cerebro necesitaba hidratarse!', 'Agua pura, sin más.', '¡Hidratación al poder!', 'El mejor líquido del planeta.', 'Me aclara la garganta para dar clase.', 'A 8 grados, la temperatura ideal.'], msgDislike: ['Preferiría algo con más sabor.', 'El agua está un poco del tiempo.', 'No tengo tanta sed.', '¿No tienes algo con cafeína?', 'Un poco aburrido.', 'Tiene un sabor a plástico...', 'Mejor la guardo para luego.'] },
    manzana: { id: 'manzana', type: 'food', name: 'Manzana', image: 'assets/images/manzana.webp', price: 10, hunger: 15, happiness: 5, msgLike: ['¡Mmm, qué manzana tan sana! 🍎', '¡Una manzana al día da alegría!', '¡Qué crujiente y dulce!', 'Perfecta para aguantar hasta el recreo.', 'Pura fibra natural.', '¡Qué jugosa!', '¡Una merienda ideal!', 'Vitaminas a tope.', 'Me recuerda a mi época de estudiante.', '¡Tiene un color precioso!'], msgDislike: ['Tiene un toque harinoso...', 'Preferiría otra fruta.', 'Esta manzana está un poco ácida.', 'Me he clavado un hueso.', 'Tiene un golpe en el lateral.', 'Tiene un gusano dentro...', 'Está un poco pocha.', 'No me apetece masticar tanto.'] },
    sandwich: { id: 'sandwich', type: 'food', name: 'Sándwich', image: 'assets/images/sandwich.png', price: 20, hunger: 25, happiness: 10, msgLike: ['Un sándwich rápido para seguir programando. 🥪', '¡Perfecto para un tentempié!', '¡El queso está fundido justo en su punto!', 'Ideal para no manchar el teclado.', '¡Vaya bocata más rico!', 'Es simple, pero me encanta.', '¡El pan de molde está súper tierno!', '¡Salvador de apuros!', 'Sabe mejor de lo que parece.', 'Un clásico que nunca falla.'], msgDislike: ['El pan está un poco seco.', 'Le falta mayonesa.', 'No es el mejor sándwich que he probado.', 'Solo tiene una loncha de jamón...', 'Los bordes están duros.', 'Es de ayer, ¿verdad?', 'Me ha tocado la tapa del pan...', 'Le falta un toque de sabor.'] },
    doritos: { id: 'doritos', type: 'food', name: 'Doritos', image: 'assets/images/doritos.png', price: 15, hunger: 10, happiness: 15, msgLike: ['¡Qué crujientes! 🧀', '¡No puedo comer solo uno!', '¡Sabor a queso a tope!', '¡Mis snacks favoritos!', 'Triángulos de pura felicidad.', '¡Ideal para la pausa!', '¡La bolsa venía súper llena!', 'Suenan genial al masticarlos.', '¡Mi vicio confesable!', 'Combina perfecto con un refresco.'], msgDislike: ['Me he manchado los dedos de naranja...', 'Demasiado salados para mi gusto.', 'Me dan mucha sed.', 'Voy a pringar todo el ratón.', 'Se me quedan entre los dientes.', 'La bolsa era 90% aire...', 'Hacen mucho ruido al comerlos en clase.'] },
    chuches: { id: 'chuches', type: 'food', name: 'Chuches', image: 'assets/images/chuches.png', price: 12, hunger: 5, happiness: 20, msgLike: ['¡Azúcar para el cerebro! 🍬', '¡Me encantan las gominolas!', '¡Un dulce capricho!', '¡Saben a mi infancia!', 'La excusa perfecta para sonreír.', '¡Directas a mis arterias!', '¡Me guardaré unas cuantas en el bolsillo!', 'Qué textura más blandita.', '¡Tienen forma de osito!', 'No me juzgues, me encantan.'], msgDislike: ['Me va a doler la barriga.', 'Tienen demasiado azúcar.', 'Se me pegan en los dientes.', 'No soy muy de chucherías.', 'Prefiero algo salado ahora mismo.', 'Estas pican demasiado.', 'Uy, creo que me he saltado un empaste.'] },
    cafe: { id: 'cafe', type: 'food', name: 'Café', image: 'assets/images/cafe.png', price: 15, hunger: 5, happiness: 20, msgLike: ['¡Oh, necesitaba este café! ☕', '¡Ahora sí puedo compilar sin errores!', '¡El combustible de los programadores!', 'Cien por cien Arábica, me gusta.', 'Elixir de los dioses.', '¡Listo para otra hora de clase!', '¡Huele que alimenta!', 'La espuma está perfecta.', 'Justo la dosis de cafeína que pedía mi cuerpo.', '¡Un espresso para despertar las ideas!'], msgDislike: ['Uf, está demasiado amargo hoy.', 'Ya he tomado demasiado café.', 'Me va a dar taquicardia.', 'Es descafeinado... vaya chasco.', 'Está un poco quemado.', 'Le falta azúcar.', 'Me he quemado la lengua...'] },
    sushi: { id: 'sushi', type: 'food', name: 'Sushi', image: 'assets/images/sushi.webp', price: 50, hunger: 30, happiness: 30, msgLike: ['¡El sushi es mi debilidad! 🍣', '¡Arigato gozaimasu!', '¡El pescado está fresquísimo!', '¡Con extra de wasabi, perfecto!', 'Un bocado exquisito.', 'Qué elegancia de comida.', '¡Salsa de soja para bañar esta maravilla!', 'Makis, nigiris... ¡me gusta todo!', 'Se nota que el chef tiene estrella Michelin.', 'Una explosión de sabor nipón.'], msgDislike: ['El arroz está un poco pasado.', 'Me he pasado con el wasabi...', 'No soy muy fan del alga nori.', 'Este salmón no me da confianza.', 'Cuesta comerlo con los palillos.', 'El jengibre pica como un demonio.', 'La salsa de soja estaba aguada.'] },
    carne: { id: 'carne', type: 'food', name: 'Carne', image: 'assets/images/carne.png', price: 45, hunger: 50, happiness: 10, msgLike: ['¡Pura proteína! 🥩', '¡Hecha justo a mi gusto!', '¡Qué festín!', 'Un chuletón de primera.', 'Me da fuerza para aguantar a la clase.', '¡Se deshace en la boca!', '¡Vuelta y vuelta, como tiene que ser!', 'Huele a barbacoa de fin de semana.', '¡Mis niveles de hierro están a tope!', 'Puntuación: 10 de 10.'], msgDislike: ['Está un poco dura...', 'Le falta un poco de sal.', 'Cuesta un poco masticarla.', 'Tiene mucho nervio.', 'La pedí muy hecha y está cruda.', 'Me voy a dejar la mandíbula aquí.', 'Tiene más hueso que carne.'] },
    macarrones: { id: 'macarrones', type: 'food', name: 'Macarrones', image: 'assets/images/macarrones.png', price: 30, hunger: 35, happiness: 15, msgLike: ['¡Macarrones con tomate, un clásico! 🍝', '¡Como los de la abuela!', '¡Están al dente!', 'Amo la comida italiana.', 'Sencillo, pero increíblemente bueno.', '¡Ñam, ñam!', '¡Con chorizo, espectacular!', 'Me podría alimentar a base de pasta.', 'Receta de estudiantes salvadora.', '¡Están en su punto de sal!'], msgDislike: ['Les falta queso rallado.', 'La salsa de tomate está un poco ácida.', 'Me he llenado enseguida.', 'Están un poco pasados de cocción.', 'Demasiado orégano.', 'Se han quedado pegados.', 'Están fríos de la nevera.'] },
    lasana: { id: 'lasana', type: 'food', name: 'Lasaña', image: 'assets/images/lasana.png', price: 35, hunger: 45, happiness: 20, msgLike: ['¡Qué rica está la lasaña! 🍽️', '¡El bechamel está espectacular!', '¡Se deshace en la boca!', 'Mi comida preferida de lejos.', 'Tiene la cantidad perfecta de carne.', '¡Menudo bloque de felicidad!', '¡Me la como entera en un suspiro!', 'Las capas de pasta están sublimes.', '¡Esto sí que levanta el ánimo!', 'Receta de oro macizo.'], msgDislike: ['Me ha caído un poco pesada.', 'Está un poco quemada por los bordes.', 'Tenía demasiada carne.', 'El tomate está algo agrio.', 'Pesa como un ladrillo.', 'Está ardiendo, ¡me he quemado!', 'Se ha desmoronado toda en el plato.'] },
    pelota: { id: 'pelota', type: 'gift', name: 'Pelota', image: 'assets/images/pelota.png', price: 10, hunger: 0, happiness: 15, msgLike: ['¡Genial, a jugar un rato! ⚽', '¡Me encanta el deporte!', '¡Gol!', '¡A dar unos toques en el pasillo!', 'Un poco de ejercicio no viene mal.', '¡Mira qué pase te hago!', '¡La final de la Champions en el recreo!', 'Bota súper bien.', 'Debería apuntarme a la liga de profesores.', '¡Paradón!'], msgDislike: ['No tengo energía para correr.', 'Preferiría algo más tranquilo.', 'Uy, casi rompo una ventana.', 'Mejor no jugar con esto aquí dentro.', 'La he pinchado sin querer.', 'Se me da fatal chutar.', 'Le di un balonazo al proyector.'] },
    boli: { id: 'boli', type: 'gift', name: 'Bolígrafo', image: 'assets/images/boli.png', price: 5, hunger: 0, happiness: 5, msgLike: ['¡Perfecto para corregir exámenes! 🖊️', '¡Qué trazo más fino!', 'Siempre viene bien un boli nuevo.', 'La tinta resbala genial.', 'Anotado para la próxima clase.', '¡Mi color favorito!', 'Tiene hasta gomita táctil.', 'No pesa nada en la mano.', '¡A firmar actas como loco!', '¡Un diseño muy profesional!'], msgDislike: ['Vaya, no escribe bien.', 'Prefiero los de tinta azul.', 'Se le ha salido la tinta.', 'Es de los baratos de propaganda.', 'Me mancha las manos.', 'El tapón está mordido...', 'Se atasca el botón al apretarlo.'] },
    microfono: { id: 'microfono', type: 'gift', name: 'Micrófono', image: 'assets/images/microfono.png', price: 25, hunger: 0, happiness: 20, msgLike: ['¡Probando, 1, 2, 3! 🎤', '¡Me encanta dar clases con micrófono!', '¡A cantar en el karaoke!', '¡Bienvenidos a mi podcast!', 'Ahora me escucharán los del fondo.', '¡Qué acústica!', 'Se me escucha con voz de locutor de radio.', '¡Cancelación de ruido incorporada, guau!', '¡Me siento como una estrella del rock!', '¡Atención, alumnos, anuncio importante!'], msgDislike: ['Hace mucho eco.', 'Me da vergüenza hablar por aquí.', 'No funciona el botón de encendido.', 'Hace una interferencia horrible.', 'Pesa demasiado para sostenerlo.', 'Tiene un pitido de fondo molesto.', 'Acabo de dejar sorda a media clase.'] },
    ordenador: { id: 'ordenador', type: 'gift', name: 'Ordenador', image: 'assets/images/ordenador.png', price: 100, hunger: 0, happiness: 40, msgLike: ['¡Vaya maquinón! 💻', '¡Ideal para programar sin lag!', '¡Gracias, el mío estaba ya muy viejo!', '¡Un procesador de ultimísima generación!', 'Tiene 64GB de RAM, ¡qué pasada!', 'Por fin puedo ejecutar mis scripts al instante.', '¡Tiene luces RGB!', 'Voy a compilar en milisegundos.', '¡Teclado mecánico, qué gustazo!', '¡Pantalla 4K para ver los errores bien claritos!'], msgDislike: ['Tiene Windows Vista...', 'El teclado es de membrana, puaj.', 'Hace mucho ruido el ventilador.', 'Tarda una hora en encender.', 'La pantalla parpadea.', 'Me han salido tres pantallazos azules.', 'No tiene suficiente tarjeta gráfica.', 'Pesa como un muerto.', 'No me gusta el sistema operativo.'] },
    osito: { id: 'osito', type: 'gift', name: 'Peluche', image: 'assets/images/osito.jpg', price: 15, hunger: 0, happiness: 15, msgLike: ['¡Qué adorable! 🧸', '¡Me lo quedo de mascota para la clase!', '¡Es súper suave!', 'Le llamaré "Gatito".', 'Será mi compañero de correcciones.', 'A mis alumnos les encantará.', '¡Da unos abrazos geniales!', 'Me quita todo el estrés del día.', 'Es imposible no sonreír al verlo.', '¡Tiene una bufandita puesta!'], msgDislike: ['Soy un poco mayor para peluches.', 'Me da alergia el polvo que coge.', 'Tiene una cara un poco rara.', 'Un ojo se le está cayendo.', 'Mejor déjalo en el armario.', 'El relleno está apelmazado.', 'Huele a cerrado.'] },
    tareas: { id: 'tareas', type: 'gift', name: 'Tareas', image: 'assets/images/tareas.png', price: 2, hunger: 0, happiness: -10, msgLike: ['¡Amo corregir! 📚', '¡Qué aplicados son mis alumnos!', '¡Trabajo extra, qué bien!', 'Me apasiona ver vuestro progreso.', 'Corregir es mi vocación.', 'Voy a coger el boli rojo con ganas.', 'Cada error es una oportunidad de aprender.', '¡Montañas de saber!', 'Me llevaré esto a casa encantado.', '¡Qué letra más bonita tienen!'], msgDislike: ['¡No más trabajo, por favor! 😭', 'Se me acumulan en la mesa...', 'Voy a llorar con tanta falta de ortografía.', 'A este paso no duermo hoy.', '¿Pero por qué copiáis todos lo mismo?', 'Esta letra es indescifrable.', 'Hay manchas de café en los folios.', 'Prefiero no mirar la nota final.', '¡Socorro, me entierran en papeles!'] },
    telefono: { id: 'telefono', type: 'gift', name: 'Teléfono', image: 'assets/images/telefono.png', price: 50, hunger: 0, happiness: 25, msgLike: ['¡Por fin podré leer el chat de clase! 📱', '¡Un modelo nuevo, genial!', '¡A descargar más apps!', 'Tiene 5G a tope.', '¡Las fotos de los apuntes saldrán nítidas!', '¡Vaya pantallón AMOLED!', '¡Tiene carga inalámbrica y todo!', 'Se acabaron los cuelgues al abrir el correo.', '¡Reconocimiento facial súper rápido!', 'Me bajaré 20 juegos educativos.'], msgDislike: ['No tiene batería.', 'La pantalla es muy pequeña.', 'No me gusta esta marca.', 'Ya me están entrando notificaciones del instituto.', 'Se ha quedado pillado abriendo WhatsApp.', 'No pilla buena cobertura aquí.', 'Se me ha resbalado y casi rompo la pantalla.', '¿Por qué tiene instalada una app de citas?'] }
};

/**
 * teachersData: Configuración base de cada profesor al iniciar la partida.
 * Define sus estadísticas base (hambre/felicidad), su avatar y sus frases ambientales específicas.
 */
const teachersData = {
    'LENGUAJE DE MARCAS': { name: 'Oskar', happiness: 50, hunger: 50, image: 'assets/images/oskar.png', phrases: ["¡Hola! Soy profe de Lenguaje de Marcas.", "¿Has cerrado el <div>?", "XML no es lo mismo que HTML.", "¡Usa etiquetas semánticas, por favor!", "Ese CSS se puede mejorar bastante.", "La accesibilidad web es vital para todos.", "¡Cuidado con el z-index!", "JSON es tu amigo, no le temas.", "El DOM es un árbol, ¡no te pierdas en sus ramas!", "¡Flexbox y Grid son la salvación del diseño!", "Recuerda: padding es hacia adentro, margin es hacia afuera.", "¿Has validado tu código en la W3C?", "¡Ponle un alt a esa imagen por dios!", "XSLT es magia pura cuando lo entiendes.", "¿Responsive design? Más bien essential design.", "Mobile first, no lo olvides.", "Un buen XPath te ahorra mil líneas de código.", "No uses tablas para el diseño, estamos en el siglo XXI.", "Tailwind está bien, pero el CSS puro curte.", "Bootstrap te saca de un apuro rápido.", "Ojo con los media queries, revisa el móvil.", "¡Centrar un div ya no es un misterio de la humanidad!", "El inspector de elementos del navegador es tu mejor amigo."], dragPhrases: ["¡Cuidado con mi camiseta de Goku!"] },
    'ENTORNOS DE DESARROLLO': { name: 'Mari Carmen', happiness: 60, hunger: 40, image: 'assets/images/maricarmen.png', phrases: ["¡Hola! ¿Has hecho commit hoy?", "En mi máquina sí funciona...", "¡Cuidado con los merge conflicts en Git!", "Documenta ese código, te lo suplico.", "Git rebase o Git merge... esa es la cuestión.", "¡Limpia los breakpoints de tu IDE!", "El debugging es un verdadero arte.", "¿Has probado a usar el depurador en lugar de console.log?", "JavaDoc no se escribe solo, ¡ánimo!", "Un buen diagrama UML vale más que mil líneas de código.", "El testing no es opcional, es una obligación.", "Agile no significa hacer las cosas sin pensar.", "Scrum, Kanban... lo importante es organizarse.", "Cuidado con los 'code smells', mantén tu código limpio.", "Refactorizar hoy te ahorrará lágrimas mañana.", "¿Has hecho push a la rama correcta?", "No dejes el código comentado en producción, ¡bórralo!", "El control de versiones te salvará la vida.", "Visual Studio Code tiene extensiones maravillosas.", "Aprende a usar los atajos de teclado, ganarás tiempo.", "Una buena suite de tests te deja dormir tranquilo por las noches.", "Cuidado con subir contraseñas a GitHub público..."] },
    'SISTEMAS INFORMÁTICOS': { name: 'Luis', happiness: 40, hunger: 60, image: 'assets/images/luis.png', phrases: ["¿Has probado a apagarlo y encenderlo otra vez?", "¡Hola! Vigila esa dirección IP.", "Linux siempre es la respuesta correcta.", "Los permisos 777 son el mal absoluto.", "¡Esa memoria RAM está a punto de explotar!", "Cuidado con dejar puertos abiertos.", "Un buen informático siempre hace copias de seguridad.", "sudo rm -rf / no es una buena idea...", "La máscara de red te está jugando una mala pasada.", "¿Has mirado en los logs del sistema?", "El modelo OSI tiene 7 capas, no te saltes ninguna.", "Virtualizar es optimizar recursos.", "Bash scripting te ahorra horas de trabajo manual.", "Windows update siempre llega en el peor momento.", "Ponle una contraseña segura al root, por favor.", "Cuidado con el firewall, te puede bloquear a ti mismo.", "El ping es el mejor amigo del administrador.", "¿DNS? Siempre es la culpa del DNS.", "Docker ha revolucionado los sistemas modernos.", "Cuidado con los cuellos de botella en el disco duro.", "No toques el registro de Windows si no sabes lo que haces.", "Montar un servidor propio enseña más que mil clases."] },
    'BASE DE DATOS': { name: 'Juan', happiness: 80, hunger: 20, image: 'assets/images/juan.png', phrases: ["SELECT * FROM alumnos WHERE felices = TRUE;", "¡Hola! Vigila esas foreign keys.", "Normalización hasta la 3FN como mínimo.", "Cuidado, casi haces un DROP TABLE.", "Un JOIN sin ON es un desastre asegurado.", "¡Optimiza esa consulta, tarda demasiado!", "Los triggers los carga el diablo.", "No olvides poner un WHERE en ese UPDATE...", "Si no haces COMMIT, es como si no hubieras hecho nada.", "Una tabla sin Primary Key es una anarquía.", "Cuidado con las inyecciones SQL, usa consultas preparadas.", "El modelo entidad-relación es la base de todo.", "Las transacciones ACID te garantizan dormir tranquilo.", "¿Has creado los índices necesarios?", "GROUP BY y HAVING, el dúo dinámico.", "No guardes las contraseñas en texto plano, usa hash.", "Las vistas te simplifican la vida.", "MongoDB está bien, pero el modelo relacional tiene su encanto.", "Usa VARCHAR en vez de CHAR si no sabes la longitud.", "Un producto cartesiano por error te tumba el servidor.", "Los diagramas E/R bien hechos ahorran reescribir código.", "Ojo con los valores NULL, pueden jugarte malas pasadas."] }
}; // Closes the teachersData object

const talkOptions = [
    { text: "¿Qué tal el día?", reply: "¡Muy bien, enseñando a tope!", change: 5 },
    { text: "Me encanta tu asignatura.", reply: "¡Me alegra escucharlo! Tienes un 10.", change: 10 },
    { text: "¡Vaya rollo de clase!", reply: "Pues a mí me apasiona... ¡A dirección!", change: -15 },
    { text: "¿Algún consejo para el examen?", reply: "Estudia los apuntes del tema 3.", change: 5 },
    { text: "He traído café para todos.", reply: "¡Eres el mejor alumno del mundo!", change: 15 },
    { text: "¿Has visto la última serie de moda?", reply: "¡Sí! El final me dejó loco.", change: 5 },
    { text: "He encontrado un bug en el código.", reply: "A ver, enséñamelo. ¡Buen ojo!", change: 10 },
    { text: "¿Puedo entregar la práctica mañana?", reply: "La fecha límite era ayer. Un 0.", change: -10 },
    { text: "¡Qué elegante vienes hoy!", reply: "¡Gracias! Me gusta arreglarme.", change: 10 },
    { text: "El wifi del centro va fatal.", reply: "Ya, he puesto un parte a mantenimiento.", change: 0 },
    { text: "¿Cuál es tu lenguaje favorito?", reply: "El que da de comer, jaja.", change: 5 },
    { text: "He usado IA para hacer el trabajo.", reply: "¡Suspenso por copiar!", change: -20 },
    { text: "Necesito ayuda con este error 404.", reply: "Revisa la ruta del archivo.", change: 5 },
    { text: "¡Feliz día del profesor!", reply: "¡Muchas gracias, qué detalle!", change: 15 },
    { text: "Creo que el proyector no funciona.", reply: "Otra vez... voy a llamar al técnico.", change: -5 },
    { text: "¿Podemos hacer clase práctica hoy?", reply: "¡Claro! Abrid los ordenadores.", change: 10 },
    { text: "He formateado mi ordenador por error.", reply: "¡Madre mía! ¿Y la copia de seguridad?", change: -10 },
    { text: "Me he leído todo el temario extra.", reply: "¡Impresionante! Así se hace.", change: 20 },
    { text: "¿Vas a ir a la excursión del viernes?", reply: "¡Por supuesto! Va a ser divertido.", change: 5 },
    { text: "Esta silla está un poco rota.", reply: "Cógela de otra mesa por ahora.", change: 0 },
    { text: "¡Madre mía, qué calor hace hoy!", reply: "Ni que lo digas, pondré el aire.", change: 5 },
    { text: "En mis tiempos programábamos en papel.", reply: "Jaja, qué exagerado.", change: 10 },
    { text: "¿Habéis visto la noticia sobre la IA?", reply: "Sí, es fascinante.", change: 15 },
    { text: "Si no te compila, revisa las comillas.", reply: "El mejor consejo del día.", change: 10 },
    { text: "¡Buen trabajo en la última práctica!", reply: "¡Gracias! Me esforcé mucho.", change: 20 },
    { text: "A ver si ordenamos un poco la mesa...", reply: "Tienes razón, qué desastre.", change: -5 },
    { text: "¿Quién ha tocado el termostato?", reply: "Yo no he sido...", change: 0 },
    { text: "He corregido los exámenes... tela.", reply: "¿Tan mal han ido?", change: -10 },
    { text: "Voy a por otro café, no puedo más.", reply: "¡Tráeme uno a mí también!", change: 10 },
    { text: "Si seguís así, vais a ser grandes profesionales.", reply: "¡Qué motivador, gracias!", change: 25 },
    { text: "El trabajo en equipo es fundamental.", reply: "Totalmente de acuerdo.", change: 15 },
    { text: "¿Alguien me presta un cargador?", reply: "Aquí tienes el mío.", change: 5 },
    { text: "Esta actualización del sistema me tiene frito.", reply: "Siempre rompen algo nuevo.", change: -5 },
    { text: "¡Silencio en la clase, por favor!", reply: "...", change: -15 },
    { text: "Hoy vamos a ver un tema muy interesante.", reply: "¡Tengo ganas de aprenderlo!", change: 15 },
    { text: "No olvidéis comentar el código.", reply: "Lo haré, lo prometo.", change: 10 },
    { text: "El diseño web no es solo poner colores.", reply: "La experiencia de usuario es clave.", change: 10 },
    { text: "La seguridad informática no es un juego.", reply: "¡Cierto! Hay que proteger los datos.", change: 15 },
    { text: "¿Habéis hecho copia de seguridad?", reply: "¡Claro que sí!", change: 10 },
    { text: "Me encanta la actitud de esta clase.", reply: "Nos esforzamos mucho.", change: 20 },
    { text: "Se me ha colgado el ordenador otra vez.", reply: "¡Qué rabia da eso!", change: -10 },
    { text: "¡Cuidado con la postura en la silla!", reply: "Es verdad, tengo la espalda fatal.", change: 5 },
    { text: "Ese error de lógica es de primero de carrera.", reply: "Ups, qué vergüenza.", change: -15 },
    { text: "Siempre hay una solución más óptima.", reply: "Seguiré buscando entonces.", change: 10 },
    { text: "¡Qué rápido pasa el tiempo cuando te diviertes!", reply: "¡La clase se me ha hecho cortísima!", change: 25 },
    { text: "¿Aprobé el último examen?", reply: "Todavía los estoy corrigiendo...", change: -5 },
    { text: "He traído galletas de chocolate.", reply: "¡Oh, ponlas en mi mesa por favor!", change: 20 },
    { text: "¿Podemos salir 5 minutos antes hoy?", reply: "De eso nada, hasta que no suene el timbre.", change: -10 },
    { text: "El perro se ha comido mi pen drive.", reply: "Esa excusa ya no cuela en el siglo XXI.", change: -15 },
    { text: "He estado practicando todo el fin de semana.", reply: "¡Esa es la actitud que busco!", change: 25 },
    { text: "¿Me explica la última parte otra vez?", reply: "Claro, para eso estoy aquí.", change: 10 },
    { text: "Me duele la cabeza de mirar tanto la pantalla.", reply: "Recuerda apartar la vista cada 20 minutos.", change: 5 },
    { text: "¡Por fin es viernes!", reply: "¡Y el cuerpo lo sabe! A descansar todos.", change: 15 },
    { text: "Hoy me siento muy productivo.", reply: "¡Esa es la energía que necesitamos!", change: 15 },
    { text: "¡Mira mi nuevo teclado mecánico!", reply: "¡Qué sonido tan satisfactorio!", change: 10 },
    { text: "He borrado la base de datos de producción.", reply: "¡¿QUE TÚ HAS QUÉ?!", change: -30 },
    { text: "¿Has visto el partido de anoche?", reply: "No soy muy de deportes, la verdad.", change: 0 },
    { text: "Necesito un aumento de sueldo.", reply: "Yo también, amigo mío.", change: 5 },
    { text: "Voy a compilar el kernel de Linux a mano.", reply: "Suerte con eso, te veo en dos semanas.", change: 10 }
];

const dragPhrases = [
    "¡Eh, suéltame!",
    "¡Que me mareo!",
    "¡Bájame ahora mismo!",
    "¡No soy un juguete!",
    "¡Voy a llamar a mi abogado de avatares!",
    "¡Me estás descolocando los píxeles!",
    "¡Tengo miedo a las alturas!",
    "¡Ay, ay, ay!",
    "¡Socorro, un secuestro alienígena!",
    "¡Ponme en el suelo firme!",
    "¡No tengo paracaídas!",
    "¡Se me va a caer el café!"
];

const bumpPhrases = [
    "¡Uy, perdón!", "¡Cuidado por donde pisas!", "¡Ouch!", "¡Ay, que chocamos!", 
    "¡Perdona, no te vi!", "¡Paso, paso!", "¡Piii piii!", "¡Aparta un poco!", 
    "¡Qué tráfico hay hoy!", "¡Señor, mire por dónde va!", "¡Vaya golpe!", 
    "¡Frena, frena!", "¡Casi me tiras!", "¡Uy, perdona el empujón!"
];

const soloPalacioPhrases = [
    "¡Cuántos profesionales hay por aquí!", "Ese stand de tecnología es brutal.", "Me voy a llevar un montón de bolis de publicidad.", 
    "Aquí hay muy buen networking.", "El catering del congreso está tremendo.", "Me encanta la arquitectura de este palacio.", 
    "A ver si me dan una camiseta gratis.", "Creo que la siguiente charla empieza ya.", "Hay un montón de empresas buscando talento aquí.", 
    "¿Nos hacemos una foto en el photocall?", "Voy a pedir financiación para mi proyecto.", "Me han dado un panfleto larguísimo.", 
    "¡Cuánta gente importante junta!", "Aquel de allí me suena de GitHub.", "Voy a dejar mi currículum en todas partes.", 
    "Esta moqueta es súper suave.", "¡Madre mía la cola para el baño!", "Voy a mirar qué venden en ese expositor.", 
    "A ver si dan muestras gratis.", "Me encanta el ambiente emprendedor.", "La conexión WiFi de aquí es muy rápida.", 
    "Voy a escanear todos los códigos QR que vea.", "Me pregunto a qué hora será el descanso.", "Hay mucho ruido de fondo.", 
    "Aquel robot del stand de robótica me está mirando raro.", "He perdido el mapa del evento.", "¿Dónde darán el café?",
    "Voy a sentarme en primera fila para esta conferencia.", "Este proyector tiene una resolución increíble.", 
    "Me están llenando la bolsa de panfletos.", "Esa pantalla gigante debe consumir muchísimo.", "¡Qué de luces LED!", 
    "La acústica de este pabellón es espectacular.", "Mira cuántas startups han venido este año.", "Me duele el brazo de dar la mano a tanta gente.",
    "A ver qué se cuece en el auditorio principal.", "Ojalá den acreditaciones con mi nombre bien escrito.", 
    "He olvidado las tarjetas de visita en la academia.", "Me voy a sentar en esas sillas de diseño moderno un rato.",
    "¿Me habrán enfocado las cámaras del evento?", "Siento que estoy en el Silicon Valley.", "Ojalá sorteasen un portátil aquí.",
    "Me está pitando el oído con tantos decibelios.", "Acabo de ver a un pez gordo de la industria de la programación."
];

const soloPlazaPhrases = [
    "¡Qué buen día hace en la plaza!", "Vamos a dar una vuelta por ahí.", "Me encanta ver a la gente pasear por aquí.", 
    "Un sitio perfecto para tomar el sol.", "¡Cuidado con las palomas!", "Podríamos montar un picnic aquí mismo.", 
    "Me relaja mucho el sonido de esta plaza.", "Podríamos ir a tomar un helado luego.", "Este sitio me inspira para programar.", 
    "¡Casi piso una cáscara de plátano!", "Mira qué nubes más bonitas.", "Hay un músico callejero muy bueno.", 
    "Deberíamos organizar clases al aire libre.", "¡Huele a churros!", "Voy a sentarme en la fuente a pensar.", 
    "Me encanta la brisa que corre aquí.", "Mira ese perrito, ¡qué mono!", "El cielo está súper azul hoy.", 
    "Voy a respirar aire puro un rato.", "Qué tranquilidad se respira.", "Voy a leer un libro bajo ese árbol.", 
    "Cuidado con los ciclistas que van rápido.", "Hace un día estupendo para no estar corrigiendo.", 
    "Ojalá traerme el portátil y trabajar desde aquí.", "¡Qué bonita es nuestra ciudad!", "¡Me acabo de tragar un mosquito!",
    "El sonido del agua de la fuente es terapéutico.", "Deberíamos hacer más excursiones así.", "Tengo la vitamina D al máximo.", 
    "Voy a echarle unas migas a los patos.", "Esa estatua del centro necesita una limpieza.", "Un ambiente muy zen.",
    "¡Uy, casi me da un niño con un balón!", "El césped está perfectamente cortado.", "Me voy a desabrochar un poco la chaqueta.",
    "¿Sabes qué falta? Un puesto de perritos calientes.", "Mira ese dibujando con tiza en el suelo.", "Qué sombra tan agradable da este pino.",
    "A lo lejos se escucha la campana de la iglesia.", "Hoy no pienso pensar en el trabajo.", "La luz natural es la mejor."
];

// s = indica el índice del interlocutor/hablante (0, 1, 2, 3) dentro de la matriz local del chat
// {0}, {1}... serán reemplazados automáticamente por los nombres de pila de los profesores que forman el grupo actual.
const hangoutDialogues2 = [
    [ {s:0, t:"¡Hola {1}! ¿Qué tal la excursión?", time: 3000}, {s:1, t:"¡Fantástica! Hacía mucha falta salir.", time: 3000}, {s:0, t:"A ver si nos tomamos un café luego.", time: 3000} ],
    [ {s:0, t:"¿Has visto el código que han subido hoy los alumnos?", time: 3500}, {s:1, t:"Sí... un desastre total, sin indentar.", time: 3500}, {s:0, t:"Tendremos que dar una clase de repaso urgente.", time: 3500}, {s:1, t:"Sin duda, mañana a primera hora.", time: 3000} ],
    [ {s:0, t:"¡Eh, {1}! ¿Te sabes el chiste del programador?", time: 3500}, {s:1, t:"Uy, a ver, sorpréndeme.", time: 2500}, {s:0, t:"Hay 10 tipos de personas...", time: 2500}, {s:1, t:"...las que saben binario y las que no. ¡Muy viejo!", time: 3500} ],
    [ {s:0, t:"Me duele la espalda de tanta silla en el centro.", time: 3500}, {s:1, t:"Yo me he comprado un cojín lumbar y mano de santo.", time: 3500}, {s:0, t:"¿Se nota la diferencia de verdad?", time: 3000}, {s:1, t:"¡Te lo recomiendo totalmente!", time: 3000} ],
    [ {s:0, t:"Oye, ¿te vienes a comer algo luego cerca de aquí?", time: 3500}, {s:1, t:"Vale, pero invitas tú esta vez.", time: 3000}, {s:0, t:"Jajaja, ¡ni de broma, a medias!", time: 3000}, {s:1, t:"Había que intentarlo...", time: 2500} ],
    [ {s:0, t:"¿Qué te parece la decoración de este lugar, {1}?", time: 3500}, {s:1, t:"Está bastante bien, muy moderno todo.", time: 3500}, {s:0, t:"Sí, tiene un rollo muy minimalista.", time: 3000} ],
    [ {s:0, t:"¡{1}! Adivina qué he aprendido hoy.", time: 3000}, {s:1, t:"¿A hacer CSS sin llorar?", time: 3000}, {s:0, t:"¡Oye! Pues casi, he dominado el flexbox.", time: 3500} ],
    [ {s:0, t:"Esta excursión es justo lo que necesitaba.", time: 3500}, {s:1, t:"Totalmente, salir del aula despeja muchísimo la mente.", time: 4000}, {s:0, t:"Y así los alumnos nos dejan en paz un rato.", time: 3500}, {s:1, t:"Jajaja, amén a eso.", time: 2500} ],
    [ {s:0, t:"¡Qué lentos andan algunos hoy!", time: 3000}, {s:1, t:"Es que no todo el mundo tiene tu energía, {0}.", time: 3500}, {s:0, t:"El secreto es tomar cuatro cafés antes de salir.", time: 3500}, {s:1, t:"Eso no puede ser bueno para el corazón...", time: 3500} ],
    [ {s:0, t:"Tengo que corregir 40 exámenes este finde.", time: 3500}, {s:1, t:"Uf, te acompaño en el sentimiento.", time: 3000}, {s:0, t:"Deberíamos automatizar esto con un script.", time: 3500}, {s:1, t:"Llevamos diciendo eso tres años, {0}.", time: 3500} ],
    [ {s:0, t:"¿Alguien ha visto las llaves de la sala de profesores?", time: 4000}, {s:1, t:"Creo que se las dejaste puestas a la puerta.", time: 3500}, {s:0, t:"¡Ay madre, a ver si nos roban los ordenadores!", time: 4000}, {s:1, t:"Tranquilo, el conserje las guardó.", time: 3500} ],
    [ {s:0, t:"¿Sabes que ayer se me cerró el IDE sin guardar?", time: 3500}, {s:1, t:"¡No fastidies! ¿Perdiste mucho?", time: 3000}, {s:0, t:"Unas tres horas de código...", time: 3000}, {s:1, t:"Te dije que activaras el auto-guardado, {0}.", time: 3500}, {s:0, t:"A partir de hoy, créeme que lo haré.", time: 3000} ],
    [ {s:0, t:"¡Qué sueño tengo, {1}!", time: 3000}, {s:1, t:"¿Te quedaste programando hasta tarde?", time: 3000}, {s:0, t:"Estaba persiguiendo un bug maldito.", time: 3500}, {s:1, t:"¿Y lo arreglaste al menos?", time: 2500}, {s:0, t:"Resultó que me faltaba un punto y coma.", time: 3500}, {s:1, t:"¡Clásico error de novato!", time: 2500} ],
    [ {s:0, t:"{1}, tengo una idea millonaria.", time: 3000}, {s:1, t:"A ver, sorpréndeme.", time: 2500}, {s:0, t:"Una app que te dice si debes ir en manga corta o larga.", time: 4000}, {s:1, t:"Eso ya existe, {0}. Se llama mirar por la ventana.", time: 4000}, {s:0, t:"Me acabas de hundir el negocio.", time: 3000} ],
    [ {s:0, t:"Oye, he pensado en comprarme un patinete eléctrico.", time: 4000}, {s:1, t:"Para venir al centro te vendría genial.", time: 3500}, {s:0, t:"El problema es si llueve.", time: 3000}, {s:1, t:"Pues te pones un chubasquero y listo.", time: 3000}, {s:0, t:"No me veo yo con tanto glamour.", time: 3000} ],
    [ {s:0, t:"El nuevo alumno hace demasiadas preguntas.", time: 3500}, {s:1, t:"Eso es bueno, demuestra interés.", time: 3000}, {s:0, t:"Pero me pregunta cosas del temario del año pasado...", time: 4000}, {s:1, t:"Bueno, tómatelo con paciencia.", time: 3000} ],
    [ {s:0, t:"Estoy pensando en cambiar mi fondo de pantalla.", time: 4000}, {s:1, t:"¿Qué tienes puesto ahora mismo?", time: 3000}, {s:0, t:"Una foto de código en verde sobre negro, muy hacker.", time: 4500}, {s:1, t:"Ponte un paisaje, te relajará la vista.", time: 3500}, {s:0, t:"Lo tendré en cuenta, gracias.", time: 3000} ],
    [ {s:0, t:"¡Cuidado, no pises ahí!", time: 2500}, {s:1, t:"¿Qué pasa? ¿Hay algo?", time: 2500}, {s:0, t:"Era broma, solo quería ver tus reflejos.", time: 3500}, {s:1, t:"Qué gracioso eres, {0}...", time: 3000} ],
    [ {s:0, t:"¿Te vienes de vacaciones a la playa este verano?", time: 4000}, {s:1, t:"Depende de cuánto cobremos extra este mes.", time: 4000}, {s:0, t:"Podríamos alquilar algo baratito a medias.", time: 4000}, {s:1, t:"Lo miramos luego si quieres.", time: 3000} ],
    [ {s:0, t:"Anoche tuve una pesadilla malísima.", time: 3500}, {s:1, t:"¿Qué soñaste?", time: 2500}, {s:0, t:"Soñé que todos mis backups estaban corruptos.", time: 4000}, {s:1, t:"¡No digas eso ni en broma!", time: 3000} ],
    [ {s:0, t:"Tengo ganas de que sea viernes otra vez.", time: 3500}, {s:1, t:"¡Pero si es martes!", time: 3000}, {s:0, t:"Lo sé, pero hay que ser previsor.", time: 3500} ],
    [ {s:0, t:"¿Alguna vez te has arrepentido de ser profesor?", time: 4000}, {s:1, t:"Solo cuando tengo que corregir exámenes en papel.", time: 4000}, {s:0, t:"Deberíamos obligarles a usar el ordenador siempre.", time: 4000}, {s:1, t:"Amén a eso, compañero.", time: 2500} ],
    [ {s:0, t:"He empezado a jugar a un MMO nuevo.", time: 3500}, {s:1, t:"Despídete de tu vida social entonces.", time: 3500}, {s:0, t:"¿Tú crees que los profesores tenemos de eso?", time: 4000}, {s:1, t:"...Tienes un punto ahí.", time: 2500} ],
    [ {s:0, t:"¿Te apetece una competición de mecanografía luego?", time: 4000}, {s:1, t:"Te destrozo, hago 120 palabras por minuto.", time: 4000}, {s:0, t:"Yo hago 150, pero con los ojos vendados.", time: 4000}, {s:1, t:"Ya, y pulsando espacio con la frente, ¿no?", time: 4000} ],
    [ {s:0, t:"Creo que voy a comprarme un teclado ergonómico partido.", time: 4500}, {s:1, t:"Yo probé uno y tardé un mes en acostumbrarme.", time: 4000}, {s:0, t:"¿Pero mejoró tu dolor de muñecas?", time: 3500}, {s:1, t:"Sí, la verdad es que vale cada céntimo.", time: 3500} ],
    [ {s:0, t:"¿Tus alumnos también usan ChatGPT para todo?", time: 3500}, {s:1, t:"¡Totalmente! Me entregan redacciones de nivel universitario.", time: 4000}, {s:0, t:"Yo les he puesto un examen a boli y papel.", time: 3500}, {s:1, t:"Jajaja, eso es ser cruel pero justo.", time: 3000} ],
    [ {s:0, t:"El WiFi se ha vuelto a caer esta mañana.", time: 3000}, {s:1, t:"Tuvimos que dar la clase usando datos del móvil.", time: 3500}, {s:0, t:"A este paso nos tocará volver a las pizarras de tiza.", time: 3500}, {s:1, t:"Ni lo menciones, qué alergia da el polvo.", time: 3000} ],
    [ {s:0, t:"¿Sabes cuál es el colmo de un programador?", time: 3000}, {s:1, t:"Dime, {0}.", time: 2000}, {s:0, t:"No poder programar sus vacaciones.", time: 3000}, {s:1, t:"...Ese chiste es más triste que gracioso.", time: 3000} ],
    [ {s:0, t:"Ayer un alumno me dijo que su perro se comió su pendrive.", time: 4000}, {s:1, t:"¿De verdad? Esa excusa es un clásico renovado.", time: 4000}, {s:0, t:"Le pedí que me trajera una radiografía del perro.", time: 4000}, {s:1, t:"¡Qué grande eres, {0}!", time: 3000} ],
    [ {s:0, t:"Necesitamos una máquina de café nueva en la sala.", time: 3500}, {s:1, t:"La actual hace ruidos como si fuera a explotar.", time: 3500}, {s:0, t:"Un día de estos nos quedamos sin sala de profesores.", time: 3500}, {s:1, t:"Deberíamos hacer una colecta.", time: 3000} ]
];

const hangoutDialogues3 = [
    [ {s:0, t:"Chicos, ¿qué os parece si hacemos una foto grupal?", time: 3500}, {s:1, t:"¡Me apunto! Poneros todos juntos.", time: 3000}, {s:2, t:"¡Esperad, que me peino un poco!", time: 3000}, {s:0, t:"¡Patataaa!", time: 2500} ],
    [ {s:0, t:"¿Habéis decidido el temario del mes que viene?", time: 3500}, {s:1, t:"Yo voy a dar bases de datos no relacionales.", time: 3500}, {s:2, t:"Y yo empezaré con JavaScript avanzado.", time: 3500}, {s:0, t:"Pobres alumnos, se les va a freír el cerebro.", time: 3500} ],
    [ {s:0, t:"Me he dejado el móvil en clase, creo.", time: 3000}, {s:1, t:"¿Quieres que te llame a ver si suena?", time: 3000}, {s:2, t:"Yo lo vi encima de la mesa del proyector.", time: 3500}, {s:0, t:"Ah, menos mal, me habíais asustado.", time: 3000} ],
    [ {s:0, t:"{1}, {2}, ¿hacemos una carrera hasta la entrada?", time: 4000}, {s:1, t:"Paso, me ahogo enseguida.", time: 3000}, {s:2, t:"¡Yo sí me apunto! Prepárate para perder.", time: 3500}, {s:0, t:"¡Uno, dos, tres, ya!", time: 2500} ],
    [ {s:0, t:"¿Alguien entiende qué está haciendo la dirección del centro?", time: 4000}, {s:1, t:"Mejor no preguntes, {0}.", time: 3000}, {s:2, t:"Yo solo vengo, doy mi clase y me voy.", time: 3500}, {s:0, t:"Esa es la actitud ganadora, sí señor.", time: 3000} ],
    [ {s:0, t:"Oídme, tengo una idea para un proyecto nuevo.", time: 3500}, {s:1, t:"A ver, ilumínanos.", time: 2500}, {s:2, t:"Espero que no sea otra red social fallida.", time: 3500}, {s:0, t:"¡Que no! Es una app para pedir comida en clase.", time: 4000}, {s:1, t:"...Te la compro.", time: 2500} ],
    [ {s:0, t:"Ayer vi una película sobre inteligencia artificial malísima.", time: 4500}, {s:1, t:"¿La de los robots que conquistan la ciudad?", time: 4000}, {s:2, t:"A mí me pareció muy realista, la verdad.", time: 3500}, {s:0, t:"Los efectos de sonido parecían de juguete.", time: 3500}, {s:1, t:"Deberíamos ir al cine los tres la próxima vez.", time: 4000} ],
    [ {s:0, t:"¿Qué os parece si aprendemos Rust?", time: 3500}, {s:1, t:"He oído que tiene una curva de aprendizaje durísima.", time: 4000}, {s:2, t:"Yo lo intenté y lloré sangre.", time: 3000}, {s:0, t:"Dicen que el compilador te ayuda muchísimo.", time: 3500}, {s:1, t:"Te ayuda a darte cuenta de que no sabes nada.", time: 4000}, {s:2, t:"Jajaja, qué crueles sois con vosotros mismos.", time: 4000} ],
    [ {s:0, t:"Qué hambre tengo, me suenan las tripas.", time: 3500}, {s:1, t:"Yo también, ¿qué comemos hoy?", time: 3000}, {s:2, t:"A mí me apetece pizza muchísimo.", time: 3500}, {s:0, t:"Yo prefiero algo más sano, como ensalada.", time: 3500}, {s:1, t:"Ensalada para ti, pizza para nosotros.", time: 3500}, {s:0, t:"¡Eh, no me dejéis tirado!", time: 3000} ],
    [ {s:0, t:"¿Quién se ha llevado mi rotulador azul de la pizarra?", time: 4500}, {s:1, t:"Yo no he sido, te lo aseguro.", time: 3000}, {s:2, t:"Ni yo, yo solo uso negro.", time: 3000}, {s:0, t:"Pues estaba en mi mesa hace cinco minutos.", time: 4000}, {s:1, t:"A lo mejor se cayó por detrás del mueble.", time: 4000}, {s:2, t:"Deberíamos atarlos con una cuerda.", time: 3500} ],
    [ {s:0, t:"Estoy pensando en dejar de usar Windows.", time: 3500}, {s:1, t:"¡Bienvenido al mundo de Linux, {0}!", time: 3500}, {s:2, t:"Yo me pasé a macOS y no vuelvo atrás.", time: 3500}, {s:0, t:"La verdad es que cada vez pide más recursos.", time: 4000}, {s:1, t:"Instálate un Ubuntu y serás feliz.", time: 3500} ],
    [ {s:0, t:"Hoy me he equivocado de aula y he entrado a otra clase.", time: 4500}, {s:1, t:"Jajaja, ¿y qué hicieron los alumnos?", time: 3500}, {s:2, t:"Seguro que se quedaron callados sin decir nada.", time: 4000}, {s:0, t:"Exacto, me puse a escribir en la pizarra un buen rato.", time: 4500}, {s:1, t:"Hasta que te diste cuenta de que no eran los tuyos.", time: 4000}, {s:0, t:"Tierra, trágame...", time: 3000} ],
    [ {s:0, t:"Me he puesto un filtro de gatito en Teams por error.", time: 4500}, {s:1, t:"¡Yo pagaría por ver eso!", time: 3000}, {s:2, t:"¿Y pudiste quitarlo?", time: 3000}, {s:0, t:"Tardé diez minutos de reloj.", time: 3500}, {s:1, t:"Me muero de risa, qué vergüenza.", time: 3500} ],
    [ {s:0, t:"¿Alguien quiere apuntarse al torneo de ajedrez?", time: 4000}, {s:1, t:"A mí me ganan en tres movimientos.", time: 3500}, {s:2, t:"Yo solo sé cómo se mueve el caballo.", time: 3500}, {s:0, t:"Menudo par de intelectuales estáis hechos.", time: 4000} ],
    [ {s:0, t:"Mi coche ha empezado a hacer un ruido rarísimo.", time: 4000}, {s:1, t:"Sube la radio para no escucharlo.", time: 3500}, {s:2, t:"Ese es el peor consejo del mundo, {1}.", time: 3500}, {s:0, t:"Yo le he hecho caso y de momento funciona.", time: 4000}, {s:2, t:"Acabaréis empujándolo, ya veréis.", time: 3500} ],
    [ {s:0, t:"Chicos, ¿espacios o tabulaciones?", time: 3000}, {s:1, t:"Espacios, por supuesto.", time: 2500}, {s:2, t:"Tabulaciones, ¡no seáis herejes!", time: 3000}, {s:0, t:"Ya estamos otra vez con la misma pelea.", time: 3000} ],
    [ {s:0, t:"¿Nos escapamos antes de la última reunión?", time: 3500}, {s:1, t:"Yo he aparcado cerca, podemos huir rápido.", time: 3500}, {s:2, t:"Nos van a pillar fijo.", time: 3000}, {s:0, t:"El que no arriesga no gana, {2}.", time: 3000} ],
    [ {s:0, t:"Hace un frío tremendo en mi clase.", time: 3000}, {s:1, t:"En la mía parece que estamos en el desierto.", time: 3500}, {s:2, t:"La climatización del centro tiene vida propia.", time: 3500}, {s:0, t:"Deberíamos programar un termostato inteligente.", time: 4000} ],
    [ {s:0, t:"¿Habéis visto la nueva serie de hackers?", time: 3000}, {s:1, t:"Sí, pulsan teclas al azar y descifran contraseñas.", time: 4000}, {s:2, t:"Me pone muy nervioso lo poco realista que es.", time: 3500}, {s:0, t:"Totalmente, ¡ni siquiera usan el ratón!", time: 3500} ],
    [ {s:0, t:"Estoy pensando en mandar un proyecto sorpresa.", time: 3500}, {s:1, t:"Tus alumnos te van a odiar, {0}.", time: 3000}, {s:2, t:"Eso curte el carácter.", time: 2500}, {s:0, t:"Exacto, la vida real no avisa con antelación.", time: 3500} ]
];

const hangoutDialogues4 = [
    [ {s:0, t:"¡Por fin estamos los cuatro fuera del centro!", time: 3500}, {s:1, t:"¡Ya era hora, necesitaba aire puro!", time: 3000}, {s:2, t:"Apoyo la moción. ¿A dónde vamos primero?", time: 3500}, {s:3, t:"¡Yo voto por buscar la cafetería más cercana!", time: 3500}, {s:0, t:"¡Adjudicado!", time: 2000} ],
    [ {s:0, t:"¿Quién ha sido el último en salir de la sala hoy?", time: 3500}, {s:1, t:"Creo que fui yo, ¿por qué?", time: 2500}, {s:2, t:"¿Apagaste el aire acondicionado, {1}?", time: 3500}, {s:1, t:"Uy... creo que no.", time: 2500}, {s:3, t:"Nos va a caer una buena bronca mañana.", time: 3500} ],
    [ {s:0, t:"Si montásemos una empresa los cuatro, nos forrábamos.", time: 4000}, {s:1, t:"Yo pongo el capital intelectual.", time: 3000}, {s:2, t:"Yo me encargo del backend seguro.", time: 3000}, {s:3, t:"Y yo del marketing. ¡Sería un exitazo!", time: 3500}, {s:0, t:"Mañana mismo registramos el nombre.", time: 3500} ],
    [ {s:0, t:"¿Os habéis dado cuenta de la que está liando el grupo A?", time: 4000}, {s:1, t:"Sí, están revolucionados perdidos.", time: 3000}, {s:2, t:"Tienen un examen sorpresa colgando de un hilo...", time: 4000}, {s:3, t:"Qué malos sois, dejadlos respirar, jaja.", time: 3500} ],
    [ {s:0, t:"¡Qué grupazo nos hemos juntado hoy!", time: 3000}, {s:1, t:"La verdad es que sí, hacemos buen equipo.", time: 3500}, {s:2, t:"Falta que nos suban el sueldo a todos.", time: 3000}, {s:3, t:"¡Ssh! Que no te oigan los jefes.", time: 3000}, {s:0, t:"Jajaja, sois los mejores.", time: 2500} ],
    [ {s:0, t:"Imaginad que nos toca la lotería a los cuatro.", time: 4000}, {s:1, t:"Yo me compro una isla desierta.", time: 3000}, {s:2, t:"Yo me monto un servidor cuántico en mi salón.", time: 4000}, {s:3, t:"Yo dono la mitad y me retiro al campo.", time: 3500}, {s:0, t:"¿Y qué hacemos el resto del día?", time: 3000}, {s:1, t:"Jugar a videojuegos, obviamente.", time: 3500}, {s:2, t:"¡Un LAN party eterno!", time: 2500} ],
    [ {s:0, t:"¿Qué superpoder os gustaría tener?", time: 3500}, {s:1, t:"Volar, sin dudarlo ni un segundo.", time: 3000}, {s:2, t:"Leer la mente a los alumnos durante los exámenes.", time: 4500}, {s:3, t:"Uy no, qué estrés leer mentes adolescentes.", time: 4000}, {s:0, t:"Yo pararía el tiempo para corregir con calma.", time: 4000}, {s:1, t:"Tú sí que sabes, {0}.", time: 2500} ],
    [ {s:0, t:"¿Alguien quiere pedir comida china para cenar luego?", time: 4000}, {s:1, t:"¡Me apetece arroz tres delicias!", time: 3000}, {s:2, t:"Yo soy más de fideos tostados y rollitos.", time: 3500}, {s:3, t:"A mí el pato a la pekinesa me vuelve loco.", time: 3500}, {s:0, t:"Entonces pedimos el menú familiar gigante.", time: 4000}, {s:1, t:"¡Genial, y pagamos entre todos!", time: 3500} ],
    [ {s:0, t:"Oye, ¿te acuerdas de cuando dábamos clase por videollamada?", time: 4500}, {s:1, t:"¡Qué pesadilla! 'Profe, tienes el micro apagado'.", time: 4000}, {s:2, t:"O los que ponían fondos virtuales del espacio.", time: 4000}, {s:3, t:"Yo daba clase en pijama por abajo, os lo confieso.", time: 4500}, {s:0, t:"¡Jajaja! Todos lo hemos hecho alguna vez.", time: 3500}, {s:1, t:"Fue una época extraña pero divertida.", time: 3500} ],
    [ {s:0, t:"¿Creéis que los alumnos se dan cuenta cuando improvisamos?", time: 4500}, {s:1, t:"Qué va, yo pongo cara muy seria y cuela.", time: 4000}, {s:2, t:"Yo les digo 'buena pregunta, buscadlo para mañana'.", time: 4500}, {s:3, t:"¡Ese es el truco definitivo del profesor!", time: 4000}, {s:0, t:"Menos mal que no soy el único que lo hace.", time: 4000} ],
    [ {s:0, t:"Propongo montar una banda de rock del profesorado.", time: 4000}, {s:1, t:"Yo toco la batería un poco.", time: 3000}, {s:2, t:"Yo canto fatal, pero le pongo actitud.", time: 3500}, {s:3, t:"Yo puedo ser vuestro mánager.", time: 3500}, {s:0, t:"¡Perfecto! Nos llamaremos 'Los Compiladores'.", time: 4000}, {s:1, t:"Me gusta el nombre, es muy friki.", time: 3500} ],
    [ {s:0, t:"¿Alguien ha probado el nuevo café de la máquina?", time: 4000}, {s:1, t:"Sabe a gasolina con agua.", time: 3500}, {s:2, t:"A mí me gusta, me despierta de golpe.", time: 3500}, {s:3, t:"Tú te beberías cualquier cosa, {2}.", time: 3500}, {s:0, t:"Creo que traeré el termo de casa a partir de ahora.", time: 4500} ],
    [ {s:0, t:"Deberíamos hacer un viaje de fin de curso los profesores.", time: 4500}, {s:1, t:"¿Sin alumnos? Me apunto.", time: 3000}, {s:2, t:"Podríamos irnos a un hotel todo incluido.", time: 4000}, {s:3, t:"Yo solo voy si hay buffet libre de postres.", time: 4000}, {s:0, t:"¡Claro que lo habrá! Lo miraré esta noche.", time: 4000} ],
    [ {s:0, t:"Si hiciéramos un equipo de eSports ganaríamos el mundial.", time: 4000}, {s:1, t:"Yo soy un paquete con el ratón.", time: 3000}, {s:2, t:"Yo solo juego a simuladores de granjas.", time: 3500}, {s:3, t:"Pues vaya equipo más lamentable haríamos.", time: 3500}, {s:0, t:"Me habéis quitado toda la ilusión.", time: 3000} ],
    [ {s:0, t:"¿Pizza con piña o sin piña? Es una pregunta seria.", time: 4000}, {s:1, t:"Con piña, siempre.", time: 2500}, {s:2, t:"¡Eso es un delito gastronómico!", time: 3000}, {s:3, t:"Yo prefiero que lleve extra de queso.", time: 3000}, {s:0, t:"Sabía que esta pregunta traería problemas.", time: 3500} ],
    [ {s:0, t:"Necesito café, nivel urgente.", time: 3000}, {s:1, t:"Yo ya voy por el quinto de hoy.", time: 3000}, {s:2, t:"Vais a terminar con taquicardia.", time: 3000}, {s:3, t:"Yo me he traído un té verde muy relajante.", time: 3500}, {s:0, t:"El té verde no compila código, {3}.", time: 3500} ],
    [ {s:0, t:"¿Quién es el profesor más estricto de nosotros?", time: 4000}, {s:1, t:"Yo creo que soy un trozo de pan.", time: 3000}, {s:2, t:"Sí, claro... suspendiste a medio curso el mes pasado.", time: 4500}, {s:3, t:"Jajaja, {2} tiene razón.", time: 3000}, {s:1, t:"¡Es que no estudian!", time: 2500} ],
    [ {s:0, t:"¿Os acordáis de los disquetes de 3.5?", time: 3500}, {s:1, t:"¡Qué tiempos! 1.44 Megabytes de pura tecnología.", time: 4000}, {s:2, t:"Yo todavía tengo uno de posavasos.", time: 3500}, {s:3, t:"Los alumnos piensan que es el icono de guardar en 3D.", time: 5000}, {s:0, t:"Me acabo de sentir muy mayor.", time: 3000} ]
];